### ISSUE TITLE
Allow user to force writing outputs into existing output directory

### ISSUE THREAD

**Issue by jpalmer37** [BCCDC-PHL/FluViewer#29]
Currently, `fluviewer` will fail if you give it the command line parameter `--outdir .` because it already exists. This was implemented to prevent overwrites of existing result folders.

Since the overwrite check is a safe design choice, I don't necessarily want to remove it. I am considering whether we could solely skip an overwrite check if `outdir` is the present working dir (`.`) and check any other outputs like normal. Open to suggestions.

**Comment by dfornika** [comment]
How about this? We add a `--force` flag that allows the user to specify that they want to proceed with analysis even if the outdir already exists.

**Comment by dfornika** [comment]
Fixed in #30
